### ISSUE TITLE
Terminal unresponsive when creating new terminal

### ISSUE THREAD

**Issue by zapcity** [spyder-ide/spyder-terminal#182] opened 2020-03-28 07:39 UTC
## Description of your problem

When I select "New terminal in current Editor file", all terminal sessions freeze. This also happens sometimes when I select "New Terminal in current working Directory".

**What steps will reproduce the problem?**

1. select "New terminal in current Editor file"

**What is the expected output? What do you see instead?**

I expect all terminal sessions to remain operational, but they all freeze. Any new terminal session is completely blank.

**Please provide any additional information below**

I installed a python 3.7 environment via conda (miniconda) and issued the commands:

- conda install spyder=4.1.1
- conda update spyder
- conda install spyder-terminal -c spyder-ide

I also tried with a python 3.8 environment, and it also doesn't work in there. 

One other thing: when I resize the Terminal window pane from left to right, the Terminal fonts scale down in size and remain that way.

## Versions and main components

* Terminal Version: 0.3.0
* Spyder Version: 4.1.1
* Python Version: 3.7.7 and 3.8.1
* Operating system: Windows 10

**Comment by goanpeca** [comment] 2020-04-04 14:09
@steff456 could you take a look at this one?

**Comment by ccordoba12** [comment] 2020-04-04 19:14
@zapcity, what happens if you open a new terminal with the default option?

**Comment by zapcity** [comment] 2020-04-09 07:37
When I press the '+' button i.e. "Open a new terminal", the behavior is the same, i.e. the original terminal window that opens with spyder becomes unresponsive, and all new terminal windows are blank.

**Comment by steff456** [comment] 2020-04-09 23:39
@zapcity can you give me an example route where this is happening?
I could not reproduce the issue of the new terminal in macOS or in Windows

![new-term](https://user-images.githubusercontent.com/20992645/78949520-5c8fdc80-7a91-11ea-9b74-ab7c182adaba.gif)

There's an issue with the font size that we will check!

**Comment by steff456** [comment] 2020-05-14 17:01
Closing this issue due to lack of response.

**Comment by zapcity** [comment] 2020-06-02 03:10
> @zapcity can you give me an example route where this is happening?

I'm not quite sure what you mean by example route.

Further to this. I have installed spyder + terminal on:

- my work laptop
- windows sandbox
- vmware with windows 10 2004

The install steps were:

- download miniconda from: https://docs.conda.io/en/latest/miniconda.html i.e. python 3.7 x64
- open up anaconda prompt
- conda create -n beta python=3.7
- activate beta
- conda install spyder=4.1.3
- conda install spyder-terminal -c spyder-ide
- start spyder

When I performed the above under the different install  environments listed above, I have the same issue. Most of the time the initial terminal has issues with the font size, but it is responsive. However when I either press "+" or "New Terminal in current working directory", the new terminal is blank, and the initial terminal is frozen.

**Comment by NA-Dev** [comment] 2020-06-10 04:57
I have the same bug.  I am on Windows 10 with the latest anaconda, spyder, and spyder-terminal. Terminal in git bash works fine. First terminal window to open in spyder works, but opening a new tab causes the first tab to become unresponsive and the new tab seems to never finish opening.

**Comment by steff456** [comment] 2020-06-26 03:12
@NA-Dev, @zapcity when the terminal is unresponsive, the other panels in Spyder stop working as well?

**Comment by zapcity** [comment] 2020-06-28 07:03
All the other panels work fine i.e. IPython console, New File/Editor, Variable explorer etc. I can continue to use Spyder just fine, however the Terminal's are completely unresponsive.

**Comment by harizjet** [comment] 2020-08-29 14:47
> I have the same bug. I am on Windows 10 with the latest anaconda, spyder, and spyder-terminal. Terminal in git bash works fine. First terminal window to open in spyder works, but opening a new tab causes the first tab to become unresponsive and the new tab seems to never finish opening.

This occur to me too. I just install anaconda, spyder, and spyder-terminal today and it happened directly after i try to used it.

**Comment by harizjet** [comment] 2020-08-30 04:48
> I have the same bug. I am on Windows 10 with the latest anaconda, spyder, and spyder-terminal. Terminal in git bash works fine. First terminal window to open in spyder works, but opening a new tab causes the first tab to become unresponsive and the new tab seems to never finish opening.

This occur to me too just after i installed it. Then it resolve after i restart my computer.

**Comment by zapcity** [comment] 2020-10-01 21:40
> This occur to me too just after i installed it. Then it resolve after i restart my computer.

I went through the same setup on a new install with spyder 4.1.5, and it's still not working. Restarting the pc does nothing.

**Comment by Shubham-253** [comment] 2021-07-03 22:44
So any solution to this?, I just installed spyder terminal and it is not accepting any inputs ( keys not working)

**Comment by steff456** [comment] 2021-07-05 16:22
Hi guys! While working on the new version of Spyder-terminal we made a lot of updates of a similar error with one of the newer versions of Pywinpty. We are going to make the release in a couple of days, so please once it is out test it and let me know if this error is still present.

**Comment by steff456** [comment] 2021-07-07 23:16
Hi everyone again! We just made the release of spyder-terminal 1.0.0 for Spyder 5.0.5. Can y'all try it out and let me know if he error still persists?

**Comment by steff456** [comment] 2022-01-10 15:10
I'm closing this issue because there wasn't a follow-up response after more than a week. If your error persists please re-open this issue and reply with the requested information.

Thanks for reporting!

**Closed by steff456** 2022-01-10 15:10 UTC
Labels: type:Bug

**Comment by Bluestonex64** [comment] 2022-03-27 01:54
I have this problem, my terminal is completly blank and the terminal is unusable, while I'm just trying to code a discord bot 
![image](https://user-images.githubusercontent.com/102447359/160263240-899dfc84-b634-44c8-85fd-86ca3a121d5c.png)
