### ISSUE TITLE
spyder not responding after installing spyder-terminal

### ISSUE THREAD

**Issue by betterze** [spyder-ide/spyder-terminal#128] opened 2018-01-23 15:07 UTC
## Description of your problem

**What steps will reproduce the problem?**

1. win10, anaconda
2. install spyder-terminal
3. not responding when open spyder, stucking in connecting to kernel

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Terminal Version:0.2.3
* Spyder Version: 3.2.6-py36_0
* Python Version:3.6
* Operating system:window10

**Comment by ccordoba12** [comment] 2018-01-23 15:15
Sorry, we don't have the resources to maintain spyder-terminal right now. Please uninstall it and continue using Spyder as normal.

**Comment by betterze** [comment] 2018-01-23 15:44
Thank you for your reply, it is sad to hear that. Do you know other way that could allow me to use bash inside spyder? otherwise i have to switch to pycharm, it will take me a lot of time to get used to a new IDE. Thank you for your effort.

**Comment by andfoy** [comment] 2018-05-31 18:38
Duplicate of #119

**Closed by andfoy** 2018-05-31 18:38 UTC
