### ISSUE TITLE
Spyder-Terminal Plugin in Spyder v5 corrupts Spyder menus

### ISSUE THREAD

**Issue by richlysakowski** [spyder-ide/spyder-terminal#296] opened 2021-12-28 20:27 UTC
## Description of your problem

I am trying to build a conda environment that includes Spyder v5 with Spyder-Notebook and Spyder-Terminal Plugins.  

I installed Spyder-Terminal into a new conda environment.

I have Spyder 5.2.1 installed in a conda virtual environment that was properly built using conda, then activated using conda 'activate', then installed conda package into the new conda environment.  

I launched Spyder from a Windows Command Console using "start cmd" command.  

I installed Spyder-Notebook v1.0.0 and Spyder-terminal v1.0.0 immediately after installing Spyder.  

Spyder 5 starts okay, but now my "View" menu is corrupted (see image below) and I cannot see ANY submenus, not just the NB or Terminal plugins are missing, but all submenus.  

I get the errors below from installing Spyder-Terminal: 

<class 'spyder_terminal.terminalplugin.TerminalPlugin'>: register was replaced by on_initialize, please check the Spyder 5.1.0 migration guide to get more information
Traceback (most recent call last):

```<class 'spyder_terminal.terminalplugin.TerminalPlugin'>: register was replaced by on_initialize, please check the Spyder 5.1.0 migration guide to get more information
Traceback (most recent call last):
  File "c:\ProgramData\Anaconda3\envs\pyTDA_pipOK\lib\site-packages\spyder\app\mainwindow.py", line 902, in setup
    plugin_instance = PLUGIN_REGISTRY.register_plugin(
  File "c:\ProgramData\Anaconda3\envs\pyTDA_pipOK\lib\site-packages\spyder\api\plugin_registration\registry.py", line 342, in register_plugin
    instance = self._instantiate_spyder5_plugin(
  File "c:\ProgramData\Anaconda3\envs\pyTDA_pipOK\lib\site-packages\spyder\api\plugin_registration\registry.py", line 193, in _instantiate_spyder5_plugin
    plugin_instance.initialize()
  File "c:\ProgramData\Anaconda3\envs\pyTDA_pipOK\lib\site-packages\spyder\api\plugins\new_api.py", line 625, in initialize
    self.on_initialize()
  File "c:\ProgramData\Anaconda3\envs\pyTDA_pipOK\lib\site-packages\spyder\api\plugins\new_api.py", line 720, in on_initialize
    raise SpyderAPIError(
spyder.api.exceptions.SpyderAPIError: register was replaced by on_initialize, please check the Spyder 5.1.0 migration guide to get more information
Traceback (most recent call last):
  File "c:\ProgramData\Anaconda3\envs\pyTDA_pipOK\lib\site-packages\spyder_terminal\widgets\main_widget.py", line 303, in __wait_server_to_start
    self.create_new_term(give_focus=False)
  File "c:\ProgramData\Anaconda3\envs\pyTDA_pipOK\lib\site-packages\spyder_terminal\widgets\main_widget.py", line 360, in create_new_term
    self, self.port, path=path, font=self.font.family(),
AttributeError: 'NoneType' object has no attribute 'family'```

**What steps will reproduce the problem?**

1. See above.  

**What is the expected output? What do you see instead?**

I was hoping that Spyder-Notebook and Spyder-Terminal would be installed and work correctly, with no detriment to my existing Spyder application.  

## Versions and main components

* Terminal Version:  1.0.0
* Spyder Version:  5.2.1
* Python Version: 3.8
* Operating system: Windows 10 (latest update, v.IDK)

![image](https://user-images.githubusercontent.com/9345711/146844541-af245db2-622e-41d4-8b92-2799e66a2e01.png)

Here's the installation commands that I used and their results for Spyder-Notebook and Spyder-Terminal:  

```(pyTDA_pipOK) c:\Users\richadmin>conda install spyder-notebook -c spyder-ide
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: c:\ProgramData\Anaconda3\envs\pyTDA_pipOK

  added / updated specs:
    - spyder-notebook


The following NEW packages will be INSTALLED:

  spyder-notebook    spyder-ide/noarch::spyder-notebook-0.1.4-py_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(pyTDA_pipOK) c:\Users\richadmin>conda install spyder-terminal -c spyder-ide
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: c:\ProgramData\Anaconda3\envs\pyTDA_pipOK

  added / updated specs:
    - spyder-terminal


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    coloredlogs-15.0.1         |   py38haa244fe_2          80 KB  conda-forge
    humanfriendly-10.0         |   py38haa244fe_1         138 KB  conda-forge
    pyreadline3-3.3            |   py38haa244fe_2         146 KB  conda-forge
    spyder-terminal-1.0.0      |   py38haa244fe_1         8.4 MB  spyder-ide
    ------------------------------------------------------------
                                           Total:         8.7 MB

The following NEW packages will be INSTALLED:

  coloredlogs        conda-forge/win-64::coloredlogs-15.0.1-py38haa244fe_2
  humanfriendly      conda-forge/win-64::humanfriendly-10.0-py38haa244fe_1
  pyreadline3        conda-forge/win-64::pyreadline3-3.3-py38haa244fe_2
  spyder-terminal    spyder-ide/win-64::spyder-terminal-1.0.0-py38haa244fe_1


Proceed ([y]/n)? y


Downloading and Extracting Packages
spyder-terminal-1.0. | 8.4 MB    | ############################################################################ | 100%
pyreadline3-3.3      | 146 KB    | ############################################################################ | 100%
coloredlogs-15.0.1   | 80 KB     | ############################################################################ | 100%
humanfriendly-10.0   | 138 KB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(pyTDA_pipOK) c:\Users\richadmin>```

**Comment by ccordoba12** [comment] 2021-12-29 18:06
Closing as a duplicate of issue #297 (it's basically the same problem and I explained to you how to fix it in spyder-ide/spyder#17115).

**Closed by ccordoba12** 2021-12-29 18:06 UTC
